name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        lfs: true

    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run start-tests

    - name: Build
      run: npm run start_build

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/shopping-test
        enable_jekyll: true
        
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: server/server
        remote: server
        rmRemote: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
